on:
  push:
    branches:
      - main
  pull_request:

name: E2E Tests

jobs:
  test-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Exec E2E Tests
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: ./ci
          args: test-exec --src .
