on:
  push:
    branches:
      - main
  pull_request:

name: E2E Tests

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker E2E Test
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: ./ci
          args: test-docker --src . stdout
